In [39]:
import numpy as np

### Vector Vector Multiplication

In [40]:
u = np.array([2, 4, 5, 6], dtype=np.float64)

In [41]:
v = np.array([1, 2, 3, 4], dtype=np.float64)

In [42]:
# In Python
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
        
    for i in range(n):
        result = result + (u[i] * v[i])

    return result

In [43]:
vector_vector_multiplication(u, v)

np.float64(49.0)

In [44]:
# In numpy
np.dot(u, v)

np.float64(49.0)

### Matrix Vector Multiplication

In [60]:
A = np.arange(12, dtype=np.float64).reshape(3,4)

In [61]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [62]:
b = np.arange(4)

In [63]:
# In python
def matrix_vector_multiplication(A, b):
    assert A.shape[1] == b.shape[0]

    num_rows = A.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(A[i], b)

    return result

In [64]:
matrix_vector_multiplication(A, b)

array([14., 38., 62.])

In [65]:
# In numpy
np.dot(A,b)

array([14., 38., 62.])

### Matrix Matrix Multiplication