In [1]:
import numpy as np

### Vector Vector Multiplication

In [2]:
u = np.array([2, 4, 5, 6], dtype=np.float64)

In [3]:
v = np.array([1, 2, 3, 4], dtype=np.float64)

In [4]:
# In Python
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
        
    for i in range(n):
        result = result + (u[i] * v[i])

    return result

In [5]:
vector_vector_multiplication(u, v)

np.float64(49.0)

In [6]:
# In numpy
np.dot(u, v)

np.float64(49.0)

### Matrix Vector Multiplication

In [7]:
A = np.arange(12, dtype=np.float64).reshape(3,4)

In [8]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [9]:
b = np.arange(4)

In [10]:
# In python
def matrix_vector_multiplication(A, b):
    assert A.shape[1] == b.shape[0]

    num_rows = A.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(A[i], b)

    return result

In [11]:
matrix_vector_multiplication(A, b)

array([14., 38., 62.])

In [12]:
# In numpy
np.dot(A,b)

array([14., 38., 62.])

### Matrix Matrix Multiplication

In [14]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
V = np.arange(12).reshape(4, 3)
V.shape[0]

4

In [19]:
def matrix_matrix_multiplication(X, Y):
    assert X.shape[1] == Y.shape[0]

    num_rows = X.shape[0]
    num_cols = Y.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        yi = Y[:, i]
        Xyi = matrix_vector_multiplication(X, yi)
        result[:,i] = Xyi

    return result
    

In [20]:
matrix_matrix_multiplication(A, V)

array([[ 42.,  48.,  54.],
       [114., 136., 158.],
       [186., 224., 262.]])

In [21]:
np.dot(A, V)

array([[ 42.,  48.,  54.],
       [114., 136., 158.],
       [186., 224., 262.]])

### Identity Matrix

In [25]:
X = np.eye(3, 3)

In [28]:
A

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [29]:
np.dot(X, A)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### Inverse Matrix

In [37]:
V

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [83]:
np.random.seed(1)
R = np.random.randint(1, 100, 9).reshape(3,3)
R

array([[38, 13, 73],
       [10, 76,  6],
       [80, 65, 17]])

In [88]:
np.linalg.det(R)

np.float64(-358084.0)

In [87]:
np.dot(R, np.linalg.inv(R))

array([[ 1.00000000e+00,  8.50014503e-17,  1.09287579e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.04083409e-17],
       [-2.08166817e-17,  1.26634814e-16,  1.00000000e+00]])

In [85]:
inv

array([[-0.00251896, -0.01263391,  0.01527575],
       [-0.00086572,  0.01450498, -0.00140191],
       [ 0.01516404,  0.00399348, -0.0077021 ]])

In [86]:
np.dot(inv, R)

array([[ 1.00000000e+00,  9.71445147e-17,  4.16333634e-17],
       [ 3.46944695e-18,  1.00000000e+00,  8.89045781e-18],
       [-2.77555756e-17,  1.21430643e-17,  1.00000000e+00]])

In [92]:
import numpy as np

np.random.seed(1)
R = np.random.randint(1, 100, 9).reshape(3,3) 
result = np.dot(R, np.linalg.inv(R))

print(np.round(result, 10))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [93]:
np.allclose(result, np.eye(3))

True