In [ ]:
import numpy as np

### Creating Array

In [3]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [4]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones([3, 8], dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
np.full(35, 1.9, dtype=np.float64)

array([1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9,
       1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9,
       1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9])

In [7]:
a = np.array([1, 3, 5, 7, 9])
a

array([1, 3, 5, 7, 9])

In [8]:
a[2] = 20
a

array([ 1,  3, 20,  7,  9])

In [9]:
np.arange(1, 10, 4, dtype=float)

array([1., 5., 9.])

In [10]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi-dimensional array

In [ ]:
a = np.array([[1, 3, 3],
               [2, 21, 5],
               [3, 24, 75]
              ])

In [12]:
a.shape

(3, 3)

In [13]:
a[:, 1]

array([ 3, 21, 24])

### Randomly generated array

In [14]:
np.random.seed(34)
np.random.rand(2,3)

array([[0.03856168, 0.78010046, 0.09270376],
       [0.63289269, 0.01389085, 0.93615854]])

In [15]:
np.random.randn(2,3)

array([[-1.56117699, -0.46425312, -0.35206234],
       [-1.28149188,  0.28929924,  0.9800285 ]])

In [16]:
np.random.random(5)

array([0.80799282, 0.82651133, 0.27168333, 0.83647644, 0.28254136])

In [17]:
np.random.seed(24)
np.random.randint(low=0, high=100, size=(5, 5))

array([[34,  3, 64, 87, 17],
       [17,  1, 79,  4, 99],
       [82, 11, 99, 15, 73],
       [18,  7, 25, 35, 95],
       [28,  0, 12, 95, 33]])

### Element-wise operation

In [33]:
a = np.linspace(0 ,100, 11)
a

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [34]:
a * 2

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180., 200.])

In [35]:
b = 10 + a / 5
b

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30.])

In [36]:
(a + b) * 20

array([ 200.,  440.,  680.,  920., 1160., 1400., 1640., 1880., 2120.,
       2360., 2600.])

### Comparison Operations

In [37]:
a >= 50

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [38]:
a > b

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [40]:
a[a < b]

array([ 0., 10.])

### Summarizing Operations

In [42]:
a

array([[ 1,  3,  3],
       [ 2, 21,  5],
       [ 3, 24, 75]])

In [45]:
a.min()

np.int64(1)

In [46]:
a.sum()

np.int64(137)

In [47]:
a.std()

np.float64(22.64105306629127)

In [48]:
a.mean()

np.float64(15.222222222222221)