In [1]:
import numpy as np

### Creating Array

In [6]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [5]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones([3, 8], dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.full(35, 1.9, dtype=np.float64)

array([1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9,
       1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9,
       1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9, 1.9])

In [16]:
a = np.array([1, 3, 5, 7, 9])
a

array([1, 3, 5, 7, 9])

In [31]:
a[2] = 20
a

array([ 1,  3, 20,  7,  9])

In [27]:
np.arange(1, 10, 4, dtype=float)

array([1., 5., 9.])

In [30]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi-dimensional array

In [44]:
 a = np.array([[1, 3, 3],
               [2, 21, 5],
               [3, 24, 75]
              ])

In [50]:
a.shape

(3, 3)

In [53]:
a[:, 1]

array([ 3, 21, 24])

### Randomly generated array

In [85]:
np.random.seed(34)
np.random.rand(2,3)

array([[0.03856168, 0.78010046, 0.09270376],
       [0.63289269, 0.01389085, 0.93615854]])

In [86]:
np.random.randn(2,3)

array([[-1.56117699, -0.46425312, -0.35206234],
       [-1.28149188,  0.28929924,  0.9800285 ]])

In [87]:
np.random.random(5)

array([0.80799282, 0.82651133, 0.27168333, 0.83647644, 0.28254136])

In [91]:
np.random.seed(23)
np.random.randint(low=0, high=100, size=(5, 5))

array([[83, 40, 73, 54, 31],
       [76, 91, 39, 90, 25],
       [51,  6, 45, 12, 49],
       [66, 75, 85, 69, 64],
       [12, 21, 48, 41, 79]])

### Element-wise operation

In [95]:
a = np.linspace(0 ,100, 11)
a

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])